test(e2e): wait for Mesh sync in multizone setup (#13297)
## Motivation

Test fail

> 2025-04-01T13:23:51.147Z INFO dataplane trying to fetch bootstrap
configuration from the Control Plane
Error: Failed to generate Envoy bootstrap config. Invalid request: mesh:
mesh "msmigration" does not exist

## Implementation information

Added wait for mesh sync

> Changelog: skip

Signed-off-by: Lukasz Dziedziak <lukidzi@gmail.com>