chore(gha): replace new line with whitespace and change to array (#12096)
## Motivation

After adding a label to the second PR, I noticed that the job failed.
This was caused by the value being split across multiple lines.
Additionally, the subsequent loop didn't recognize it as an array but
instead treated it as an array of individual characters.

```
PRs with 'ci/verify-stability' label: 11672
11296
PRs with 'ci/verify-stability-merge-master' label: 1[16](https://github.com/kumahq/kuma/actions/runs/12000059034/job/33448712899#step:5:17)72
Error: Unable to process file command 'output' successfully.
Error: Invalid format '11296'
```

## Implementation information

* Changed new line to whitespace
* Change the string into an array and iterate over it

## Supporting documentation

https://github.com/kumahq/kuma/actions/runs/12000059034/job/33448712899

Fix #XX

<!--
> Changelog: skip
-->
<!--
Uncomment the above section to explicitly set a [`> Changelog:` entry
here](https://github.com/kumahq/kuma/blob/master/CONTRIBUTING.md#submitting-a-patch)?
-->

Signed-off-by: Lukasz Dziedziak <lukidzi@gmail.com>