test(e2e): failing test `should create MeshRetry policy` (#13627)
## Motivation


https://github.com/kumahq/kuma/actions/runs/15238665779/job/42856597866#step:12:1147

```
• [FAILED] [3.942 seconds]
MeshRetry [It] should create MeshRetry policy
github.com/kumahq/kuma/test/e2e_env/kubernetes/meshretry/api.go:43

Captured StdOut/StdErr Output

  [FAILED] Expected
      <[]string | len:1, cap:1>: [
          "mesh-retry-all-meshretry-api.kuma-system",
      ]
  to be empty
Error: It 05/25/25 14:46:34.336
```

## Implementation information

Instead of creating mesh with default policies and removing them
afterwards, we can simply create mesh without default policies.

---------

Signed-off-by: Ilya Lobkov <ilya.lobkov@konghq.com>